name: spam-env
channels:
  - default
  - conda-forge
dependencies:
  - python=3.7
  - pip=20.2.2
  - spacy-model-en_core_web_lg
  - pip:
    - pandas
    - scikit-learn
    - matplotlib
    - ipykernel
    - seaborn
    - imblearn
    - tensorflow
    - spacy
    - gensim
    - langdetect
    - wordcloud
    - kaggle