name: pytest
run-name: ${{ github.actor }} is learning GitHub Actions by running pytest
on: [push]
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python Stuff
        uses: actions/setup-python@v4
        with:
          python-version: '3.7' 
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: spam-env
          environment-file: conda-env.yml
          python-version: 3.7
          auto-activate-base: false
      - run: |
          conda info
          conda list
          pip install -r tests-requirements.txt
          export PYTHONPATH=.
          python -m pytest