name: pytest
run-name: ${{ github.actor }} is learning GitHub Actions by running pytest
on: [push]
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r tests-requirements.txt
      - run: export PYTHONPATH=.
      - run: pytest