name: pytest
run-name: ${{ github.actor }} is learning GitHub Actions by running pytest
on: [push]
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python Stuff
        uses: actions/setup-python@v4
        with:
          python-version: '3.7' 
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
      # - run: conda env create conda-env.yml && conda activate spam-env
      - run: pwd
      - run: ls
      - run: pip install -r tests-requirements.txt
      - run: export PYTHONPATH=.
      - run: python -m pytest
